spring.application.name=rankview
server.port=8088

# Database configuration (SQLite)
spring.datasource.url=jdbc:sqlite:rankview.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JSP View configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# Naver Search API Configuration
naver.api.client-id=ooHYVi75fSasfvaSI1Bs
naver.api.client-secret=4Jqo9dfEy2
